version: '2'
services:
  elasticsearch:
    hostname: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.16
    ports:
      - 127.0.0.1:9200:9200
    environment:
      - cluster.name=docker-es
      - bootstrap.memory_lock=true
      - bootstrap.system_call_filter=false
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    mem_limit: 4g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    #Internal network for the containers
    networks:
      - elk-stack
  kibana:
    hostname: kibana
    image: docker.elastic.co/kibana/kibana:5.6.16
    ports:
      - 127.0.0.1:5601:5601
    mem_limit: 2g
    environment:
      - "LS_JAVA_OPTS=-Xmx1g -Xms1g"
    # Internal network for the containers
    networks:
      - elk-stack
    # We don't start Kibana until the ES instance is ready
    depends_on: ['elasticsearch']
networks:
  elk-stack:
